<?php

declare(strict_types=1);

namespace Jostkleigrewe\OpenAiCoreBundle\Dto\Client\Core;

use Symfony\Component\Serializer\Annotation;

/**
 * Represents the url or the content of an image generated by the OpenAI API.
 *
 * @link https://platform.openai.com/docs/api-reference/images/object
 */
class Image
{
    /**
     * The base64-encoded JSON of the generated image, if response_format is b64_json.
     *
     * @var string|null $url
     * @Annotation\SerializedName("url")
     */
    public ?string $url;

    /**
     * The URL of the generated image, if response_format is url (default).
     *
     * @var string|null $b64_json
     * @Annotation\SerializedName("b64_json")
     */
    public ?string $b64_json;

    /**
     * @param string|null $url
     * @param string|null $b64_json
     */
    public function __construct(?string $url, ?string $b64_json)
    {
        $this->url = $url;
        $this->b64_json = $b64_json;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): Image
    {
        $this->url = $url;
        return $this;
    }

    public function getB64Json(): ?string
    {
        return $this->b64_json;
    }

    public function setB64Json(?string $b64_json): Image
    {
        $this->b64_json = $b64_json;
        return $this;
    }
}