jostkleigrewe_open_ai_core:
    apikey: '%env(resolve:OPENAI_APIKEY)%'


framework:

  # https://symfony.com/doc/current/http_client.html
  http_client:
    scoped_clients:
      open_ai_client:
        base_uri: 'https://api.openai.com'
        headers:
          Authorization: 'Bearer %env(resolve:OPENAI_APIKEY)%'
          Content-Type: 'application/json'
