jostkleigrewe_open_ai_core:
    apikey: '%env(resolve:OPENAI_APIKEY)%'

framework:
  http_client:
    scoped_clients:
      open_ai_client:
        base_uri: 'https://api.openai.com/v1/'
        headers:
          Authorization: 'Bearer %env(resolve:OPENAI_APIKEY)%'
          Content-Type: 'application/json'